import React from "react"
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DevInfo | Multivalue State</title>
        <meta name="google-site-verification" content="4YTM9hykvzsweTONT0RJliVYAO1kMBioSB61lAVoUbE" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div></div>
      </main>
    </>
  )
}

export default Home
